Repository ihmeuw/pseudopeople, pull requests merged in 2023-10, with the labels that each got.

#318 Add missingness descriptions to datasets and noises pages
  docs/source/datasets/index.rst
  docs/source/noise/column_noise.rst
Labels: documentation

#320 Add write_wrong_digits to age column in noise table
  docs/source/noise/index.rst
Labels: documentation

#322 Missingness descriptions hotfix
  docs/source/datasets/index.rst
  docs/source/noise/column_noise.rst
Labels: documentation, hotfix

#323 Fix incorrect select options CSV
  CHANGELOG.rst
  src/pseudopeople/data/incorrect_select_options.csv
Labels: bug

#324 Scale copy-from noise with correct denominator
  CHANGELOG.rst
  src/pseudopeople/noise_scaling.py
Labels: bug

#335 Drop index from simulated population data
  src/pseudopeople/loader.py
  tests/integration/test_interface.py
Labels: bug
