Repository ihmeuw/pseudopeople, pull requests merged in 2023-08, with the labels that each got.

#237 Ensure all noise functions are verbs
  docs/source/noise/column_noise.rst
  docs/source/noise/index.rst
Labels: documentation

#238 Add link to pseudopeople website in readthedocs
  docs/source/index.rst
Labels: documentation

#240 Add middle name and sex columns to SSA dataset
  docs/source/datasets/index.rst
  docs/source/noise/column_noise.rst
  docs/source/noise/index.rst
Labels: documentation

#241 Add year columns in Census, WIC, and tax datasets
  docs/source/datasets/index.rst
Labels: documentation

#235 Add 1040 to noise table in pseudopeople docs
  docs/source/noise/index.rst
Labels: documentation

#244 Fix middle name/middle initial rows in noise table
  docs/source/noise/index.rst
Labels: documentation

#245 Change income column to wages for W2 and 1099
  docs/source/datasets/index.rst
  docs/source/noise/index.rst
Labels: documentation

#254 DOC: Reorder noise functions in user docs
  docs/source/noise/column_noise.rst
  docs/source/noise/index.rst
Labels: documentation

#262 Hot fix: remove age from WIC dataset in pseudopeople docs
  docs/source/datasets/index.rst
Labels: documentation, hotfix

#258 Edit introduction page based on doc session feedback
  docs/source/index.rst
Labels: documentation

#272 Set default noise values for W2/1099 correctly
  src/pseudopeople/configuration/generator.py
Labels: bug

#274 Check the length of possible_age_differences
  src/pseudopeople/configuration/validator.py
Labels: bug

#279 Fix do_not_respond age intervals
  src/pseudopeople/constants/data_values.py
Labels: bug

#280 Use different seed for each shard and noise type
  src/pseudopeople/interface.py
  src/pseudopeople/noise.py
  src/pseudopeople/noise_functions.py
  src/pseudopeople/utilities.py
  tests/integration/test_interface.py
  tests/unit/test_column_noise.py
Labels: bug

#269 Update glossary
  docs/source/glossary.rst
Labels: documentation
