Repository ihmeuw/pseudopeople, pull requests merged in 2023-07, with the labels that each got.

#200 Update noise table to include choose the wrong option
  docs/source/noise/index.rst
Labels: documentation, hotfix

#203 Add GQ values to 'relationship to reference person' in census dataset table - hot fix
  docs/source/datasets/index.rst
Labels: documentation, hotfix

#218 Match date formats to concept model
  docs/source/datasets/index.rst
  src/pseudopeople/constants/metadata.py
  src/pseudopeople/entity_types.py
  src/pseudopeople/interface.py
  src/pseudopeople/noise.py
  src/pseudopeople/noise_functions.py
  src/pseudopeople/schema_entities.py
  tests/integration/test_interface.py
  tests/unit/test_column_noise.py
  tests/unit/test_configuration.py
Labels: bug

#195 DOC: add link to mailing list signup page
  README.rst
  docs/source/index.rst
Labels: documentation, hotfix

#216 Doc hotfix: Correct date formats
  docs/source/datasets/index.rst
Labels: documentation, hotfix

#223 Hot fix: remove references to wages from noise table
  docs/source/noise/index.rst
Labels: documentation, hotfix

#229 DOC: Add columns to decennial census and ACS
  docs/source/datasets/index.rst
  docs/source/noise/index.rst
Labels: documentation, enhancement

#224 Link to example access request
  .github/ISSUE_TEMPLATE/data_access_request.yml
Labels: hotfix
